### ISSUE TITLE
Compiler Crashes

### ISSUE THREAD

**Issue by zeelorenc** [oscar-broman/md-sort#2]
Usually the fix is to run pawncc.exe in compatability mode and compile again. But for some reason, compiling time doubles!

What I noticed is that it crashes exactly at these two lines.
https://github.com/oscar-broman/md-sort/blob/master/md-sort.inc#L41-L42

Here's my fix:
```pawn
stock SortDeepArray_Entry(&{Float, String, string, _}:cmp1, &_:cmp2, size, bool:cmp_float = false, bool:cmp_string = false, bool:ignorecase = false, E_SORT_ORDER:order = SORT_ASC, array[][], ...) {
	if (cmp_string)
		g_sort_cmp_type = 's';
	else if (cmp_float) // added cmp_float in the stock
		g_sort_cmp_type = 'f';
	else
		g_sort_cmp_type = 'i';
```

**Comment by oscar-broman** [comment]
This fix would break existing code sorting on float fields.

What other includes do you have and in what order?

**Comment by zeelorenc** [comment]
it doesn't matter what includes I have, it just crashes automatically

os: windows 8.1
flags -d3 -r

**Comment by Y-Less** [comment]
I also just got this one, but I fixed it simply by adding brackets around `tagof (Float:)` (don't ask my why that helped).
